version: '3'
services:

    nginx:
        container_name: todolist_nginx-container
        build: ./nginx
        restart: always
        ports:
        - "80:80"
        volumes:
        - api_data:/docker_api
        - ./log:/var/log/nginx
        depends_on:
        - api

    api:
        container_name: todolist_api-container
        build: ./RestfulAPI
        restart: always
        command: uwsgi --ini uwsgi.ini
        volumes:
        - api_data:/docker_api
        
volumes:
    api_data:
